"""HTML report generation — produces a self-contained, styled report."""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from naijaeval.metrics.base import MetricResult

_STYLE = """
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 960px; margin: 40px auto; padding: 0 20px;
         background: #fafafa; color: #1a1a1a; }
  h1 { color: #1a1a1a; border-bottom: 3px solid #2563eb; padding-bottom: 8px; }
  h2 { color: #374151; margin-top: 32px; }
  .meta { background: #f3f4f6; border-radius: 8px; padding: 16px;
          margin-bottom: 24px; font-size: 0.9em; }
  .meta span { margin-right: 24px; }
  .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 32px; }
  .summary-table th { background: #2563eb; color: white; padding: 10px 16px;
                       text-align: left; }
  .summary-table td { padding: 10px 16px; border-bottom: 1px solid #e5e7eb; }
  .summary-table tr:nth-child(even) td { background: #f9fafb; }
  .score { font-weight: 700; font-size: 1.1em; }
  .score-good { color: #16a34a; }
  .score-warn { color: #d97706; }
  .score-bad  { color: #dc2626; }
  .details { background: #fff; border: 1px solid #e5e7eb; border-radius: 8px;
             padding: 16px; margin-bottom: 16px; }
  .details summary { cursor: pointer; font-weight: 600; color: #2563eb; }
  pre { background: #f3f4f6; padding: 12px; border-radius: 6px;
        overflow-x: auto; font-size: 0.85em; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px;
           font-size: 0.75em; font-weight: 600; background: #dbeafe; color: #1d4ed8; }
</style>
"""


def _score_class(score: float, higher_is_better: bool) -> str:
    if higher_is_better:
        if score >= 0.7:
            return "score-good"
        if score >= 0.4:
            return "score-warn"
        return "score-bad"
    else:
        if score <= 0.1:
            return "score-good"
        if score <= 0.3:
            return "score-warn"
        return "score-bad"


def to_html(
    results: dict[str, MetricResult],
    model: str = "unknown",
    benchmark: str = "unknown",
    metadata: dict[str, Any] | None = None,
) -> str:
    """Render evaluation results as a self-contained HTML report.

    Args:
        results: Dict of metric_name → MetricResult.
        model: Model identifier.
        benchmark: Benchmark name.
        metadata: Extra metadata shown in the report header.

    Returns:
        HTML string (self-contained, no external dependencies).
    """
    rows = []
    detail_blocks = []

    for name, result in results.items():
        score = result.score
        fmt_score = f"{score:.4f}"
        css = _score_class(score, higher_is_better=True)  # default direction
        rows.append(
            f"<tr><td>{html.escape(name)}</td>"
            f'<td class="score {css}">{fmt_score}</td>'
            f"<td>{html.escape(result.description if hasattr(result, 'description') else '')}</td></tr>"
        )
        if result.details:
            detail_json = html.escape(json.dumps(result.details, indent=2, ensure_ascii=False))
            detail_blocks.append(
                f"<details class='details'><summary>{html.escape(name)} — details</summary>"
                f"<pre>{detail_json}</pre></details>"
            )

    meta_html = f"""
    <div class="meta">
      <span><strong>Benchmark:</strong> {html.escape(benchmark)}</span>
      <span><strong>Model:</strong> {html.escape(model)}</span>
      <span><strong>Metrics evaluated:</strong> {len(results)}</span>
    </div>
    """

    table = f"""
    <table class="summary-table">
      <thead><tr><th>Metric</th><th>Score</th><th>Notes</th></tr></thead>
      <tbody>{''.join(rows)}</tbody>
    </table>
    """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NaijaEval Report — {html.escape(benchmark)}</title>
  {_STYLE}
</head>
<body>
  <h1>NaijaEval Evaluation Report</h1>
  {meta_html}
  <h2>Summary</h2>
  {table}
  <h2>Metric Details</h2>
  {''.join(detail_blocks) if detail_blocks else '<p>No details available.</p>'}
  <hr>
  <p style="font-size:0.8em;color:#9ca3af;">
    Generated by <a href="https://github.com/Uchebuzz/naijaeval">NaijaEval</a>
  </p>
</body>
</html>"""


def save_html(
    results: dict[str, MetricResult],
    path: str | Path,
    model: str = "unknown",
    benchmark: str = "unknown",
    metadata: dict[str, Any] | None = None,
) -> Path:
    """Save evaluation results as an HTML report file.

    Returns:
        The resolved output path.
    """
    out = Path(path)
    out.write_text(to_html(results, model=model, benchmark=benchmark, metadata=metadata), encoding="utf-8")
    return out
